# Set docker version to this python version
FROM python:3.7-slim-stretch
# Create a directory within docker called 'crawler'
WORKDIR /crawler
# Copy the local requirements.txt file to a file and call it docker_requirements.txt in docker
COPY requirements.txt docker_requirements.txt
# Copy all files with .py extension in local proj to the workdir
COPY *.py ./
# Do the same for csv files
COPY *.csv ./
# Run pip install on the docker_requirements.txt
RUN pip install -r docker_requirements.txt

RUN apt-get install -y tzdata
ENV TZ Asia/Singapore
# Run python main.py at the end
CMD python main.py
